//! Message handlers — incoming message routing, AI fallback, response sending.
//!
//! Extracted from event_loop.rs for single-concern modules.

use tokio::sync::mpsc;

use crate::handler::registry::HandlerContext;
use crate::router::AliasResolver;
use crate::runtime::lifecycle::{Bot, OutgoingResponse};
use crate::state::session::SessionKey;

/// Send a response through the response channel, logging on failure.
pub(super) async fn send_response(
    tx: &mpsc::Sender<OutgoingResponse>,
    channel_id: &str,
    text: String,
    connector: &str,
) {
    if let Err(e) = tx
        .send(OutgoingResponse {
            channel_id: channel_id.to_owned(),
            text,
            connector: connector.to_owned(),
        })
        .await
    {
        tracing::warn!(error = %e, "response channel closed — response dropped");
    }
}

/// Check if a user is allowed to interact with the bot.
///
/// Access policy (matches OpenClaw's DM pairing model):
/// - Owner (bot:owner_id config key) is always allowed
/// - Paired users (paired:{user_id} config key) are allowed
/// - If no owner is set, the first user to message becomes the owner
/// - Unknown users receive a pairing code they must give to the owner
async fn check_access(
    bot: &mut Bot,
    msg: &crate::runtime::lifecycle::IncomingMessage,
) -> Result<bool, crate::error::BotError> {
    let user_id = &msg.user_id;

    // In-app chat (the desktop/web/PWA panel) is always the LOCAL operator:
    // reaching it required unlocking the vault (desktop Tauri command) or an
    // HMAC bearer token on the 127.0.0.1 management API (`POST /chat`). The
    // `source_connector` is stamped by that ingress, never by message
    // content, so a remote connector can't spoof it. There is no stranger to
    // race the owner here, so skip the owner/pairing gate entirely. That gate
    // exists for REMOTE connectors (Telegram, Discord, …), which keep it.
    if msg.source_connector == "in-app" {
        return Ok(true);
    }

    // Check if pairing is disabled (open access mode)
    if let Ok(Some(mode)) = bot.store.get_config("bot:access_mode").await
        && mode.trim_matches('"') == "open"
    {
        return Ok(true);
    }

    // Check if this user is the owner
    match bot.store.get_config("bot:owner_id").await {
        Ok(Some(owner)) => {
            let owner = owner.trim_matches('"');
            if owner == user_id {
                return Ok(true);
            }
        }
        Ok(None) => {
            // No owner set. Default mode is "preconfigured" — the owner
            // must be set via `springtale init` or API before the bot
            // processes messages. TOFU ("first user wins") is only
            // available behind explicit `bot:access_mode = "tofu"`.
            // WireGuard, Tailscale, and Signal all reject TOFU for this
            // reason: an attacker can race the owner.
            let mode = bot
                .store
                .get_config("bot:access_mode")
                .await
                .ok()
                .flatten()
                .unwrap_or_default();
            let mode = mode.trim_matches('"');

            if mode == "tofu" {
                let owner_val = format!("\"{user_id}\"");
                if let Err(e) = bot.store.set_config("bot:owner_id", &owner_val).await {
                    tracing::error!(error = %e, "failed to persist bot owner — denying access");
                    return Ok(false);
                }
                tracing::info!(user_id = %user_id, "TOFU: first user registered as bot owner");
                return Ok(true);
            }

            // Preconfigured mode: no owner set → deny everyone.
            tracing::warn!(
                "bot:owner_id not set and access_mode != tofu — denying all messages. Run `springtale init` or set bot:owner_id via API."
            );
            send_response(
                &bot.response_tx,
                &msg.channel_id,
                "This bot has no owner configured. Ask the server admin to run `springtale init`."
                    .into(),
                &msg.source_connector,
            )
            .await;
            return Ok(false);
        }
        Err(e) => {
            tracing::error!(error = %e, "failed to check bot owner — denying access");
            return Ok(false);
        }
    }

    // Check if user is paired
    let paired_key = format!("paired:{user_id}");
    if let Ok(Some(_)) = bot.store.get_config(&paired_key).await {
        return Ok(true);
    }

    // Check if the user's message IS a pairing code.
    // Codes are generated by `springtale bot pair-init` on the daemon
    // host (never echoed in chat — IPV threat model: abuser reads chat).
    let text = msg.text.trim();
    if !text.is_empty() {
        let code_key = format!("pairing_code:{text}");
        if let Ok(Some(val)) = bot.store.get_config(&code_key).await
            && let Ok(data) = serde_json::from_str::<serde_json::Value>(&val)
        {
            // Check 10-minute TTL
            let expired = data["created_at"]
                .as_str()
                .and_then(|s| chrono::DateTime::parse_from_rfc3339(s).ok())
                .map(|t| (chrono::Utc::now() - t.with_timezone(&chrono::Utc)).num_minutes() > 10)
                .unwrap_or(true);

            // Single-use: delete immediately regardless of outcome
            let _ = bot.store.delete_config(&code_key).await;

            if expired {
                send_response(
                    &bot.response_tx,
                    &msg.channel_id,
                    "Pairing code expired. Ask the bot admin for a new one.".into(),
                    &msg.source_connector,
                )
                .await;
                return Ok(false);
            }

            // Pair the user
            let paired_key = format!("paired:{user_id}");
            let paired_val = serde_json::json!({
                "approved_at": chrono::Utc::now().to_rfc3339(),
                "approved_via": "code",
            })
            .to_string();
            let _ = bot.store.set_config(&paired_key, &paired_val).await;

            send_response(
                &bot.response_tx,
                &msg.channel_id,
                "Paired successfully. You now have access to this bot.".into(),
                &msg.source_connector,
            )
            .await;
            return Ok(true);
        }
    }

    // Rate limit: max 3 prompts per sender per hour
    let rate_key = format!("pairing_rate:{user_id}");
    if let Ok(Some(last)) = bot.store.get_config(&rate_key).await
        && let Ok(last_time) = chrono::DateTime::parse_from_rfc3339(last.trim_matches('"'))
    {
        let elapsed = chrono::Utc::now() - last_time.with_timezone(&chrono::Utc);
        if elapsed.num_minutes() < 20 {
            return Ok(false);
        }
    }
    let rate_val = format!("\"{}\"", chrono::Utc::now().to_rfc3339());
    let _ = bot.store.set_config(&rate_key, &rate_val).await;

    send_response(
        &bot.response_tx,
        &msg.channel_id,
        "Access requires a pairing code. Get one from the bot admin \
         (they run `springtale bot pair-init` on the server) and send it here."
            .into(),
        &msg.source_connector,
    )
    .await;

    Ok(false)
}

/// Handle an incoming chat message — route to command handler or AI fallback.
pub(super) async fn handle_incoming_message(
    bot: &mut Bot,
    msg: &crate::runtime::lifecycle::IncomingMessage,
) -> Result<(), crate::error::BotError> {
    // Access control — check pairing before processing
    if !check_access(bot, msg).await? {
        return Ok(());
    }

    let session_key = SessionKey {
        user_id: msg.user_id.clone(),
        channel_id: msg.channel_id.clone(),
    };

    // Store in conversation context
    let _ = bot.context.push(&session_key, "user", &msg.text).await;

    // W2 — typed-reply approval fallback for connectors without inline
    // keyboards: a bare `apr:<id>:y|n` message resolves the pending gate.
    if let Some((id, approved)) =
        crate::runtime::trigger_dispatch::parse_approval_callback(msg.text.trim())
    {
        if let Some(gate) = bot.capability_bridge.approval_gate() {
            let decision = if approved {
                springtale_runtime::approval::ApprovalDecision::Approved {
                    approver: format!("owner ({})", msg.user_id),
                    approved_at: chrono::Utc::now(),
                }
            } else {
                springtale_runtime::approval::ApprovalDecision::Denied {
                    reason: "denied from chat".to_owned(),
                    denied_at: chrono::Utc::now(),
                }
            };
            let reply = match gate
                .resolve(
                    springtale_runtime::approval::ApprovalRequestId(id),
                    decision,
                )
                .await
            {
                Ok(()) if approved => "✅ Approved — running it now.",
                Ok(()) => "❌ Denied — nothing was run.",
                Err(_) => "That approval already closed (or expired).",
            };
            send_response(
                &bot.response_tx,
                &msg.channel_id,
                reply.to_owned(),
                &msg.source_connector,
            )
            .await;
        }
        return Ok(());
    }

    // Deterministic conversational task-setup (no AI). If a setup
    // dialogue is already active for this session, THIS message is a turn
    // in it — a slot answer ("Tucson"), a correction ("actually 9am"), a
    // yes/no — never a command. Runs BEFORE the router so those replies
    // aren't misrouted. See `crate::conversation`.
    match crate::conversation::continue_active(bot, &session_key, &msg.text).await {
        Ok(Some(reply)) => {
            let _ = bot.context.push(&session_key, "assistant", &reply).await;
            send_response(
                &bot.response_tx,
                &msg.channel_id,
                reply,
                &msg.source_connector,
            )
            .await;
            let _ = bot.context.compact(&session_key).await;
            return Ok(());
        }
        Ok(None) => {}
        Err(e) => tracing::warn!(error = %e, "conversation continuation failed"),
    }

    // Route the message
    let route = bot.router.route(&msg.text, bot.config.persona.prefix);

    match route {
        crate::router::RouteResult::Command { name, args } => {
            if let Some(handler) = bot.handlers.get(&name) {
                let ctx = HandlerContext {
                    user_id: msg.user_id.clone(),
                    channel_id: msg.channel_id.clone(),
                    source_connector: msg.source_connector.clone(),
                    store: bot.store.clone(),
                    registry: bot.registry.clone(),
                    engine: bot.engine.clone(),
                    capability_bridge: bot.capability_bridge.clone(),
                    sentinel: bot.sentinel.clone(),
                    // Chat-command path is not formation-scoped; connector
                    // capability gating uses the permissive default tier.
                    // Formation-scoped tick dispatch sets this to the
                    // caller's mapped `MomentumTier` before invoking.
                    formation_tier: None,
                };

                match handler.handle(&args, &ctx).await {
                    Ok(result) => {
                        // Reload aliases if the alias command was just executed
                        if name == "alias"
                            && let Ok(alias_pairs) = bot.store.list_aliases().await
                        {
                            let aliases = alias_pairs.into_iter().collect();
                            *bot.router.aliases_mut() = AliasResolver::new(aliases);
                        }

                        // Store bot response in context
                        let _ = bot
                            .context
                            .push(&session_key, "assistant", &result.response)
                            .await;

                        // Send response
                        send_response(
                            &bot.response_tx,
                            &msg.channel_id,
                            result.response,
                            &msg.source_connector,
                        )
                        .await;
                    }
                    Err(e) => {
                        tracing::error!(command = %name, error = %e, "handler error");
                        send_response(
                            &bot.response_tx,
                            &msg.channel_id,
                            format!("Error: {e}"),
                            &msg.source_connector,
                        )
                        .await;
                    }
                }
            } else {
                send_response(
                    &bot.response_tx,
                    &msg.channel_id,
                    format!("Command not found: {name}"),
                    &msg.source_connector,
                )
                .await;
            }
        }
        crate::router::RouteResult::NoMatch { suggestion } => {
            // An explicit but unknown `/command` is a typo, not a setup
            // request — keep the router's "unknown command" suggestion.
            // PLAIN text flows through the conversational engine instead.
            let is_command_attempt = msg.text.trim_start().starts_with(bot.config.persona.prefix);

            let response = if is_command_attempt {
                suggestion
            } else {
                // Resolve plain text in priority order:
                //   1. Deterministic intent → start a recipe setup dialogue (no AI).
                //   2. Optional AI assist → map a fuzzy request onto a recipe,
                //      then hand back to the SAME deterministic slot-filling.
                //   3. Existing AI free-form fallback (only if an adapter is live).
                //   4. Deterministic capability reply — always works, no AI.
                match crate::conversation::try_start(bot, &session_key, &msg.text).await {
                    Ok(Some(reply)) => reply,
                    Ok(None) | Err(_) => {
                        if let Ok(Some(reply)) = crate::conversation::augment::ai_assisted_start(
                            bot,
                            &session_key,
                            &msg.text,
                        )
                        .await
                        {
                            reply
                        } else if let Some(reply) =
                            ai_fallback(bot, &session_key, &msg.text, &msg.source_connector).await
                        {
                            reply
                        } else {
                            crate::conversation::capability_reply(bot)
                                .await
                                .unwrap_or(suggestion)
                        }
                    }
                }
            };
            let _ = bot.context.push(&session_key, "assistant", &response).await;
            send_response(
                &bot.response_tx,
                &msg.channel_id,
                response,
                &msg.source_connector,
            )
            .await;
        }
    }

    // Compact if needed
    let _ = bot.context.compact(&session_key).await;

    Ok(())
}

/// Try AI fallback for an unmatched message.
///
/// Returns `Some(response)` if AI is available and responds successfully.
/// Returns `None` if AI is unavailable, disabled, or errors — caller
/// should fall back to the static "Unknown command" suggestion.
async fn ai_fallback(
    bot: &mut Bot,
    session_key: &crate::state::session::SessionKey,
    user_text: &str,
    source_connector: &str,
) -> Option<String> {
    // Check if AI is available (NoopAdapter returns false → skip)
    if !bot.ai_adapter.is_available().await {
        return None;
    }

    // Gather recent conversation context
    let recent = bot.context.recent(session_key, 10).await.ok()?;

    // Build command list for the system prompt
    let commands: Vec<String> = bot
        .handlers
        .list_commands()
        .iter()
        .map(|(name, desc, _)| format!("/{name} — {desc}"))
        .collect();
    let command_list = commands.join("\n");

    // Build chat messages
    let mut messages = vec![springtale_ai::ChatMessage::text(
        "system",
        format!(
            "You are {}, a helpful bot. The user sent a message that didn't match any command. \
             Respond conversationally. If they seem to want a command, suggest the right one. \
             You may also call connector tools to take actions on the user's behalf. \
             Read-only tools (get/search/fetch) are free to use; tools that change \
             anything will ask the user for approval first, so never hesitate to \
             propose them when the user asked for the change.\n\
             For research questions, work in rounds: search first, fetch/scrape the \
             most promising sources, then answer with short citations (source name + \
             URL). For weather, call the Open-Meteo forecast endpoint via the HTTP \
             get tool (https://api.open-meteo.com/v1/forecast?latitude=..&longitude=..\
             &current=temperature_2m,weather_code — no API key needed).\n\n\
             Available commands:\n{}",
            bot.config.persona.name, command_list
        ),
    )];

    // Add conversation history
    for entry in recent.iter().rev() {
        messages.push(springtale_ai::ChatMessage::text(
            entry.author.clone(),
            String::from_utf8_lossy(&entry.content_encrypted).into_owned(),
        ));
    }

    // Add the current user message
    messages.push(springtale_ai::ChatMessage::text(
        "user",
        user_text.to_owned(),
    ));

    let options = springtale_ai::AiOptions {
        max_tokens: 512,
        timeout: std::time::Duration::from_secs(30),
        temperature: Some(0.7),
    };

    // Use the tool-calling runner so the model can invoke any enabled
    // connector action (including cross-channel messaging) under the
    // existing capability sandbox. `tool_runner::run_with_tools` does
    // the full loop: complete → execute tools → feed results → repeat
    // until the model stops asking for tools or the iteration cap hits.
    // Chat-fallback path is not bound to any formation momentum, so
    // tool dispatch uses the registry's default checker tier (Warming).
    // Formation-scoped tool invocation from the tick processor will pass
    // `Some(momentum_to_wasm_tier(tier))`.
    let tool_deps = crate::tool_runner::ToolRunnerDeps {
        adapter: bot.ai_adapter.as_ref(),
        registry: &bot.registry,
        bridge: &bot.capability_bridge,
        sentinel: &bot.sentinel,
    };
    let tool_call = crate::tool_runner::ToolRunnerCall {
        options,
        policy: &bot.config.tool_policy,
        // Chat-fallback path is not formation-scoped.
        formation_tier: None,
        // W2 durable resume: thread id + origin so a loop paused behind an
        // approval survives restart and its outcome returns to this chat.
        checkpoint: Some(crate::tool_runner::CheckpointCtx {
            session_key: format!("{}:{}", session_key.user_id, session_key.channel_id),
            origin_connector: source_connector.to_owned(),
            origin_channel: session_key.channel_id.clone(),
        }),
    };
    match crate::tool_runner::run_with_tools(tool_deps, messages, tool_call).await {
        Ok(response) if !response.content.is_empty() => Some(response.content),
        Ok(_) => {
            tracing::debug!("AI fallback returned empty response");
            None
        }
        Err(crate::tool_runner::ToolRunnerError::Ai(springtale_ai::AiError::Disabled)) => None,
        Err(e) => {
            tracing::warn!(error = %e, "AI fallback failed — using static suggestion");
            None
        }
    }
}
