"""Type stubs for the compiled extension.

Curated surface, per the crate's module documentation: the cooperation
model, not the runtime. Keep in step with `src/` — the classes here are
the ones `module.rs` registers.
"""

from enum import Enum
from typing import Optional

__version__: str

class MomentumTier(Enum):
    """Capability gate. Cold, Warming, Hot, Fever."""

    Cold = ...
    Warming = ...
    Hot = ...
    Fever = ...

class Intent:
    """A formation's intent pattern."""

    @staticmethod
    def reconnoiter(target: str) -> "Intent": ...
    @staticmethod
    def execute(plan_id: Optional[str] = None) -> "Intent": ...
    @staticmethod
    def stabilize(reason: str) -> "Intent": ...
    @staticmethod
    def surge(objective: str) -> "Intent": ...
    @staticmethod
    def dissolve(reason: str) -> "Intent": ...
    def kind(self) -> str:
        """``"reconnoiter" | "execute" | "stabilize" | "surge" | "dissolve"``."""

class FormationId:
    """A formation's identity, a UUID seen from Python as a string."""

    def __init__(self) -> None: ...
    @staticmethod
    def parse(s: str) -> "FormationId": ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class Formation:
    """A read-only handle over a formation: identity, intent, momentum."""

    def __init__(self, intent: Intent) -> None: ...
    @property
    def id(self) -> FormationId: ...
    @property
    def intent(self) -> Intent: ...
    @property
    def momentum_tier(self) -> MomentumTier: ...
