[package]
name = "springtale-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
indicatif = { workspace = true }
tabled = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rpassword = { workspace = true }
figment = { workspace = true }
hex = { workspace = true }
toml = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
springtale-core = { workspace = true }
springtale-crypto = { workspace = true }
springtale-connector = { workspace = true }
springtale-store = { workspace = true }
