//! Event subscription handles for trigger lifecycle management.
//!
//! When `on_event()` registers a handler, it returns a `Subscription`
//! containing an opaque ID. The caller stores this handle and passes
//! it to `remove_event()` when the rule is disabled, deleted, or updated.
//!
//! Pattern: Home Assistant's detach callback / n8n's ITriggerResponse.closeFunction.

use std::sync::atomic::{AtomicU64, Ordering};

/// Opaque identifier for a registered event handler.
///
/// Generated by the connector when `on_event()` is called.
/// Used by `remove_event()` to locate and remove the handler.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct SubscriptionId(pub u64);

/// Handle returned by `on_event()`. Store per-rule for lifecycle management.
///
/// Contains the subscription ID and the trigger name it was registered for.
/// Pass to `remove_event()` to tear down the handler.
#[derive(Debug)]
pub struct Subscription {
    /// Unique ID for this registration.
    pub id: SubscriptionId,
    /// Trigger name this handler was registered for.
    pub trigger: String,
}

/// Atomic counter for generating unique subscription IDs within a connector.
///
/// Each connector instance owns one of these. IDs are unique per-connector,
/// not globally — this is sufficient since `remove_event` is called on the
/// same connector that issued the subscription.
pub struct SubscriptionCounter(AtomicU64);

impl SubscriptionCounter {
    /// Create a new counter starting at 1.
    pub fn new() -> Self {
        Self(AtomicU64::new(1))
    }

    /// Generate the next unique subscription ID.
    pub fn next(&self) -> SubscriptionId {
        SubscriptionId(self.0.fetch_add(1, Ordering::Relaxed))
    }
}

impl Default for SubscriptionCounter {
    fn default() -> Self {
        Self::new()
    }
}
