//! Cross-module aggregate — one enum any cooperation-layer caller can
//! return. `From` impls are auto-generated by `#[from]`, so each sub-error
//! converts with `?` into this aggregate.

use thiserror::Error;

use super::awareness::AwarenessError;
use super::cadence::CadenceError;
use super::commit::CommitError;
use super::consensus::ConsensusError;
use super::formation::FormationError;
use super::handoff::HandoffError;
use super::interference::InterferenceError;
use super::momentum::MomentumError;
use super::pacing::PacingError;
use super::rally::RallyError;
use super::recovery::RecoveryError;

#[derive(Debug, Error)]
pub enum CooperationError {
    #[error(transparent)]
    Cadence(#[from] CadenceError),
    #[error(transparent)]
    Formation(#[from] FormationError),
    #[error(transparent)]
    Momentum(#[from] MomentumError),
    #[error(transparent)]
    Awareness(#[from] AwarenessError),
    #[error(transparent)]
    Consensus(#[from] ConsensusError),
    #[error(transparent)]
    Commit(#[from] CommitError),
    #[error(transparent)]
    Interference(#[from] InterferenceError),
    #[error(transparent)]
    Rally(#[from] RallyError),
    #[error(transparent)]
    Recovery(#[from] RecoveryError),
    #[error(transparent)]
    Handoff(#[from] HandoffError),
    #[error(transparent)]
    Pacing(#[from] PacingError),
    #[error(transparent)]
    Store(#[from] springtale_store::StoreError),
    #[error("gossip: {0}")]
    Gossip(String),
    #[error("liveness: {0}")]
    Liveness(String),
    #[error("capability bridge: {0}")]
    Bridge(String),
    #[error("role: {0}")]
    Role(String),
    #[error("internal invariant violated: {0}")]
    Invariant(String),
}
