//! Cross-module aggregate — one enum any cooperation-layer caller can
//! return. `From` impls are auto-generated by `#[from]`, so each sub-error
//! converts with `?` into this aggregate.

use thiserror::Error;

use super::awareness::AwarenessError;
use super::cadence::CadenceError;
use super::commit::CommitError;
use super::consensus::ConsensusError;
use super::formation::FormationError;
use super::handoff::HandoffError;
use super::interference::InterferenceError;
use super::momentum::MomentumError;
use super::pacing::PacingError;
use super::rally::RallyError;
use super::recovery::RecoveryError;

#[derive(Debug, Error)]
pub enum CooperationError {
    #[error(transparent)]
    Cadence(#[from] CadenceError),
    #[error(transparent)]
    Formation(#[from] FormationError),
    #[error(transparent)]
    Momentum(#[from] MomentumError),
    #[error(transparent)]
    Awareness(#[from] AwarenessError),
    #[error(transparent)]
    Consensus(#[from] ConsensusError),
    #[error(transparent)]
    Commit(#[from] CommitError),
    #[error(transparent)]
    Interference(#[from] InterferenceError),
    #[error(transparent)]
    Rally(#[from] RallyError),
    #[error(transparent)]
    Recovery(#[from] RecoveryError),
    #[error(transparent)]
    Handoff(#[from] HandoffError),
    #[error(transparent)]
    Pacing(#[from] PacingError),
    #[error(transparent)]
    Store(#[from] springtale_store::StoreError),
    #[error("COOP-C001 gossip: {0}")]
    Gossip(String),
    #[error("COOP-C002 liveness: {0}")]
    Liveness(String),
    #[error("COOP-C003 capability bridge: {0}")]
    Bridge(String),
    #[error("COOP-C004 role: {0}")]
    Role(String),
    #[error("COOP-C005 internal invariant violated: {0}")]
    Invariant(String),
}

impl CooperationError {
    /// J1 — stable error ID. Each variant returns the same prefix the
    /// Display impl emits, suitable for `springtale fix <id>` lookup.
    /// Transparent sub-error variants delegate to the sub-error's
    /// `code()`; the few free-standing string variants carry their own
    /// `COOP-C00x` IDs.
    pub fn code(&self) -> &'static str {
        match self {
            Self::Cadence(e) => e.code(),
            Self::Formation(e) => e.code(),
            Self::Momentum(e) => e.code(),
            Self::Awareness(e) => e.code(),
            Self::Consensus(e) => e.code(),
            Self::Commit(e) => e.code(),
            Self::Interference(e) => e.code(),
            Self::Rally(e) => e.code(),
            Self::Recovery(e) => e.code(),
            Self::Handoff(e) => e.code(),
            Self::Pacing(e) => e.code(),
            // `springtale_store::StoreError` doesn't expose a stable id —
            // we surface a single bucket so the fix-registry can still
            // address it.
            Self::Store(_) => "COOP-C000",
            Self::Gossip(_) => "COOP-C001",
            Self::Liveness(_) => "COOP-C002",
            Self::Bridge(_) => "COOP-C003",
            Self::Role(_) => "COOP-C004",
            Self::Invariant(_) => "COOP-C005",
        }
    }
}
